[build-system]
build-backend = "mesonpy"
requires = [
    "meson-python",
    "setuptools_scm >= 2.1",
    "cython >= 0.28.1",
]

[project]
name = "uharfbuzz"
version = "0.0.1"

[tool.cibuildwheel]
# only build for 64-bit
skip = ["*-manylinux_i686", "*-musllinux*"]

test-requires = "pytest"
test-command = "pytest {project}/tests"

[tool.cibuildwheel.macos]
archs = ["x86_64", "universal2", "arm64"]
before-all = "brew install ccache"
before-test = "ccache --show-stats"

[tool.cibuildwheel.macos.environment]
CC = "/usr/local/opt/ccache/libexec/cc"

[tool.cibuildwheel.linux]
before-all = [
    "yum install -y ccache",
    "ln -s $(which ccache) /usr/lib64/ccache/gcc",
]
before-test = "ccache --show-stats"

[tool.cibuildwheel.linux.environment]
CC = "/usr/lib64/ccache/gcc"
CFLAGS = "-g0"
